### ISSUE TITLE
放弃了吗

### ISSUE THREAD

**Issue by xiangfeigao** [maicong/qmusic#1]
这个放弃了吗

**Comment by maicong** [comment]
现在很少用 QQ 音乐听歌了，这个项目不更新了哦，你可以将红心歌单 ID 改为你自己的。
对应位置：
https://github.com/maicong/qmusic/blob/244928a7a0e1667b7ee0dea654993de3ee57ff19/index-src.php#L80
https://github.com/maicong/qmusic/blob/244928a7a0e1667b7ee0dea654993de3ee57ff19/index.php#L82
